# Generated by Django 3.0 on 2022-06-23 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0016_auto_20220310_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_db',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='master_db',
            name='week_start',
        ),
    ]
