# Generated by Django 3.0 on 2022-06-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0018_auto_20220623_0553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_db',
            name='week_end',
        ),
        migrations.RemoveField(
            model_name='master_db',
            name='week_start',
        ),
    ]
